apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dev-app
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/AndreCbrera/gitops_repository
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-app
  namespace: flux-system
spec:
  interval: 10m
  path: "./apps/dev-app/overlays/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-app
